In [1]:
float(4+int(2.39)%2)

4.0

In [2]:
float(22//3+3/3)

8.0

In [5]:
D = dict(p='San',q='foundry')
'{p}{q}'.format(**D)

'Sanfoundry'

In [6]:
x = 'abcd'
for i in x:
    print(i.upper())

A
B
C
D


In [7]:
for i in range(int(float('inf'))):
    print(i)

OverflowError: cannot convert float infinity to integer

In [8]:
'ab'.zfill(5)

'000ab'

In [1]:
s = 'Hello'
s.__getitem__(3)

'l'

In [2]:
print('Hello!2world@#'.istitle())

False


In [3]:
a=[1,2,3,4]
b = [sum(a[0:x+1]) for x in range(0,len(a))]
b

[1, 3, 6, 10]

In [6]:
a=[[]]*3
a[1].append[7]
a

TypeError: 'builtin_function_or_method' object is not subscriptable

# shifting digits 1 position left 

In [11]:
a = [1,2,3,4,5,6]
for i in range(1,6):
    a[i-1] = a[i]

for i in range(0,6):
    print(a[i],end =' ')

2 3 4 5 6 6 

In [14]:
a={3,4,5}
b={5,6,7}
a+b

TypeError: unsupported operand type(s) for +: 'set' and 'set'

In [16]:
a=2,3,4,5
a

(2, 3, 4, 5)

In [17]:
a={1,2,3}
a.intersection_update({3,4,5})
a

{3}

In [44]:
import collections 
b = dict()
b = collections.defaultdict(int)
b[1]

0

In [24]:
x=abcd
print(list(map(list,x)))

NameError: name 'abcd' is not defined

In [26]:
a = reduce(lambda x:x-3 in range(4,10))
print(list(m))

NameError: name 'reduce' is not defined

In [27]:
x=[[0],[1]]
print((''.join(list(map(str,x)))))

[0][1]


In [28]:
math.fact(6)

NameError: name 'math' is not defined

In [1]:
def check(n):
    if n < 2:
        return n % 2 == 0
    return check(n-2)
print(check(11))

False


In [6]:
import time
t = (2010,9,20,8,15,12,6)
time.asctime(t)

TypeError: asctime(): illegal time tuple argument

In [56]:
import re
sentence = 'we are humans'
m = re.match(r'(.*)(.*?)(.*)',sentence)
print(m.groups())

('we are humans', '', '')


In [14]:
'%(qty)d more %(food)s'%{'qty':1,"food":'spam'}

'1 more spam'

In [15]:
float(22//3+3/3)

8.0

In [16]:
x=34
print("%f"%x)

34.000000


In [23]:
"{0:.2f}".format(1.234)

'1.23'

In [24]:
x=(i for i in range(0,3))
for i in x:
    print(i)
for i in x:
    print(i)

0
1
2


In [25]:
s='\t\tWorld\n'
s.strip()

'World'

In [26]:
for i in range(float('inf')):
    print(i)

TypeError: 'float' object cannot be interpreted as an integer

In [27]:
print("Hello{0!r}and{0!s}".format('foo','bin'))


Hello'foo'andfoo


In [28]:
print('cd'.partition('cd'))

('', 'cd', '')


In [29]:
l1=[11,22,3]
l2=[11,22,1]
l1 < l2

False

In [30]:
s='He123'
len(s)

5

In [34]:
'xyyzxyzxzxyy'.count('yy')

2

In [46]:
x=[[1],[2]]
print((''.join(list(map(str,x))),))

('[1][2]',)


In [37]:
t=(1,2,4,3)
t[1:-1]

(2, 4)

In [41]:
a=[1,4,3,5,2]
b =[4,1,2,3,5]
a==b


False

In [40]:
set(a)==set(b)

True

In [42]:
a={5,6,7}
sum(a,5)

23

In [49]:
l1=[1,2,3,[4]]
l2=list(l1)
id(l1)==id(l2)

False

In [50]:
import math
math.fsum([.1 for i in range(20)])

2.0

In [52]:
math.isfinite(float("0.0"))

True

In [54]:
x=['ab','cd']
print(len(map(list,x)))

TypeError: object of type 'map' has no len()

In [1]:
str1="python class"
print (''.join(str1.split()[::-1]))

classpython


In [8]:
list1= ['Python', 10, 20, ['Hello', 30.40, [11, 22, [97, 98, 99], 33] , 50], 66, 78]
# print(list1[3][2][2][2])
print(list1[-3][-2][-2][-2])



98


In [9]:
list1= [1, 2, 3, 4, 5, 6, 7, 8, 9]
print (list1[2:7:-1])

[]


In [15]:
inp_str = "Learnbay classes"
inp_str.find('ss')

12

In [22]:
def foo():
     try:
            print(1)
     finally:
           print(2)
foo()

1
2


In [24]:
9+99+999+9999

11106

In [ ]:
b = int(a)
while i >= 0:
    b += i*a
    i -= 1
    if i == 1:
        break
print(b)

In [1]:

odd = []
for i in a:
    if i % 2 != 0:
        odd.append(i)
print("Odd Series is:",odd)

Odd Series is: [1, 3, 5, 7, 9]


In [3]:
a= [1,2,3,4,5,6,7,8,9]
b = [i**2 for i in a if i % 2 != 0]
print(b)

[1, 9, 25, 49, 81]


In [17]:
a = input("Enter any num:")
b = a*2
c = a*3
d = a*4
m = int(a)
n = int(b)
p = int(c)
q = int(d)
print("Total of a+aa+aaa+aaaa:",m + n + p + q)

Enter any num:9
Total of a+aa+aaa+aaaa: 11106


In [8]:
x = [1,2,3]
y = [-1,0.1,1.1] + x[0:2]
print((y))

[-1, 0.1, 1.1, 1, 2]


In [9]:
x = [7,8,9]
y = [-3.3,-2,3.2] + x[0:2]
print(len(y))

5


In [19]:
print(type(type(bool(1))))

<class 'type'>


# Learnbay Codes as per chapter

# 1. Garbage collection module : PVM manages memory internally

In [21]:
import gc
print(dir(gc),'\n')
print(gc.isenabled(),'\n')
gc.disable()
print(gc.isenabled(),'\n')
gc.enable()
print(gc.isenabled(),'\n')

['DEBUG_COLLECTABLE', 'DEBUG_LEAK', 'DEBUG_SAVEALL', 'DEBUG_STATS', 'DEBUG_UNCOLLECTABLE', '__doc__', '__loader__', '__name__', '__package__', '__spec__', 'callbacks', 'collect', 'disable', 'enable', 'freeze', 'garbage', 'get_count', 'get_debug', 'get_freeze_count', 'get_objects', 'get_referents', 'get_referrers', 'get_stats', 'get_threshold', 'is_finalized', 'is_tracked', 'isenabled', 'set_debug', 'set_threshold', 'unfreeze'] 

True 

False 

True 



# 2.use of \ escape sequence

In [22]:
a = 10
b = 20
if a\          # \ escape sequence used to write single line statements into multiple line statements
<b:
    print(a)
else:
    print(b)

10


# 5. use of sorted & sort function 

In [ ]:
''' 
sorted() Function : 
>>>It sorts the given sequence either in Ascending or Descending order(depending on reverse & key attributes inside its syntax) 
>>>It returns a sorted LIST always & the original sequnece remains unaffected.
>>> It can perform operations on sequence data type(list,str,tuple) & also on non sequence dict & set data types


sort() Function:
>>> It can only be used on list data type.
>>> It changes the original sequence.
>>> It returns nothing as o/p.

'''


In [29]:
# Use case for sorted function with diff data types
s = 'bat'    
s1=['a','1','y']
s2 = 1,4,0
s3 = {'s','q','rat'}
s4 = {'name':'sha','id': 6952,'D.O.B': 111993}

print(sorted(s))
print(sorted(s1,key = len))
print(sorted(s2))
print(sorted(s3,reverse = True))
print(sorted(s4))

['a', 'b', 't']
['a', '1', 'y']
[0, 1, 4]
['s', 'rat', 'q']
['D.O.B', 'id', 'name']


In [30]:
s=['b','a','t']    # use of list data type for sort. better to use sorted() rather than .sort() method
s.sort()
s

['a', 'b', 't']

# Sorted List

In [41]:
sample_list = []
n = int(input("Enter count of strings to add:"))
for i in range(n):
    n1 = input("Enter strings:")
    sample_list.append(n1)
print("Ascending Sorted list is:",sorted(sample_list))
print("Sorted list as per key len:",sorted(sample_list, key = len))
print("Descending Sorted list:",sorted(sample_list, reverse = True))

Enter count of strings to add:3
Enter strings:Delhi
Enter strings:Hyd
Enter strings:Bombay
Ascending Sorted list is: ['Bombay', 'Delhi', 'Hyd']
Sorted list as per key len: ['Hyd', 'Delhi', 'Bombay']
Descending Sorted list: ['Hyd', 'Delhi', 'Bombay']


# count of letters in any str from user

In [44]:
m = input("Enter any str:")
n = 0
for i in m:
    n += 1
print(m,n)

Enter any str:shashank
shashank 8


# To append sub str into middle of main str using lists

In [12]:
main_str = input("Enter main str:")
len1 = len(main_str)
sub_str =  input("Enter sub str:")
len2 = len(sub_str)
n = int(input("Enter position:"))
n -= 1
new_list = []

for i in range(n):
    new_list.append(main_str[i])
for i in range(len2):
    new_list.append(sub_str[i])
for i in range(n,len1):
    new_list.append(main_str[i])
new_list = "".join(new_list)
print(new_list)

Enter main str:shashank
Enter sub str:HELLO
Enter position:3
shHELLOashank


# To concatenate sub str into middle of main str using str 

In [1]:
main_str = input("Enter main str:")
len1 = len(main_str)
sub_str =  input("Enter sub str:")
len2 = len(sub_str)
n = int(input("Enter position:"))
n -= 1
new_str = ''

for i in range(n):
    new_str += main_str[i]
for i in range(len2):
    new_str += sub_str[i]
for i in range(n,len1):
    new_str += main_str[i]
print(new_str)

Enter main str:Shashank
Enter sub str:HELLO
Enter position:3
ShHELLOashank


# 6. Control Statements

# Use of While Loop

In [4]:
x = 100
while x >= 100 and x <= 110:
    print(x)
    x += 2

100
102
104
106
108
110


# for-else statements

In [17]:
#else block always executed irresoective of for statement executed or not 

a=[1,2,3,4,5]
b = int(input("Enter num to find:"))
for i in a:
    if i == b:
        print("Element found")
else:
    print("Element not found")

Enter num to find:4
Element found
Element not found


# 7.Lists 

# Aliasing Operation (Shallow Copy)

In [24]:
a = [1,2,3,4,5]
b = a
a[2] = 0
print("a:",a,"b:",b)

a: [1, 2, 0, 4, 5] b: [1, 2, 0, 4, 5]


# Clone or Copy Operation (Deep Copy)

In [25]:
a = [1,2,3,4,5]
b = a[:]
a[2] = 0
print("a:",a,"b:",b)

a: [1, 2, 0, 4, 5] b: [1, 2, 3, 4, 5]


In [26]:
a = [1,2,3,4,5]
b = list(a)
a[2] = 0
print("a:",a,"b:",b)

a: [1, 2, 0, 4, 5] b: [1, 2, 3, 4, 5]


In [30]:
a = [1,2,3,4,5]
b.copy()
a[2] = 0
print("a:",a,"b:",b)

a: [1, 2, 0, 4, 5] b: [1, 2, 3, 4, 5]


# 8.Tuples

In [8]:
num = eval(input())   # eval() accepts str as arguments & returns evaluated expression in the form of integer o/p
sum = 0
n = len(num)
for i in range(n):
    sum += i
print("Sum is:",sum)
print("Avg is:",sum/n)

1,2,3,4,5
Sum is: 10
Avg is: 2.0


In [14]:
num = eval(input())
print(num)

1+2+3
6


# Adding elements into an existing immutable tuple sequence

In [59]:
names = 'Ajay','Vijay','Suresh','Jay'
lst = [input("Enter name to insert")]
new = tuple(lst)
pos = int(input("Where to insert ?:") )

names1 = names[0:pos-1]
names1 += new
names1 += names[pos-1:] 
print(names1)

Enter name to insertshashank
Where to insert ?:3
('Ajay', 'Vijay', 'shashank', 'Suresh', 'Jay')


## Replacing an element in an immutable tuple sequence

In [70]:
names = 'Ajay','Vijay','Suresh','Jay'
lst = [input("Enter a name to replace:")]
new = tuple(lst)
pos = int(input("Enter position:"))

names1 = names[0:(pos-1)]
names1 += new
names1 += names[pos:]
print(type(names1), names1)

Enter a name to replace:Shashank
Enter position:3
<class 'tuple'> ('Ajay', 'Vijay', 'Shashank', 'Jay')


# Deleting elements from an immutable tuple sequence

In [17]:
a = ['shashank','uday','sadadekar']
n = input()
for i in range(len(a)-1):
    if a[i] != n:
        continue
    else:
        del a[i]
b = tuple(a)
print(b)
print(type(b))

shashank
('uday', 'sadadekar')
<class 'tuple'>


# 9.Dictionaries

In [3]:
d = eval(input())

{'A':1,'B':2}


# Adding 2 dicts

In [24]:
A = {1:'a',2:'b'}
B = {1:1,2:2}
A|B

{1: 1, 2: 2}

In [25]:
A = {1:'a',2:'b'}
B = {3:1,4:2}
A|B

{1: 'a', 2: 'b', 3: 1, 4: 2}

# Taking key value pairs from user to create a dict

In [2]:
x = {}
print("How many pairs?")
n = int(input())
for i in range(n):
    print("Enter keys:")
    k = (input())
    print("Enter values:")
    v = int(input())
    x.update({k:v})
print(x)

How many pairs?
3
Enter keys:
raj
Enter values:
10
Enter keys:
sonal
Enter values:
5
Enter keys:
Ram
Enter values:
15
{'raj': 10, 'sonal': 5, 'Ram': 15}


In [26]:
d = {}
print("How many pairs?")
n = int(input())
for i in range(n):
    print("Enter player name:")
    k = input()
    print("Enter score:")
    v = int(input())
    d.update({k:v})
print(d)

# for names in d:
#     print("Player Names:",names)

name = input("Enter player's name")
runs = d.get(name,-1)
# print(score)
# print(d.keys())
if runs != -1:
    print(f"Player {name} scored {v} runs")
else:
    print("player not found")


How many pairs?
2
Enter player name:
dhoni
Enter score:
3
Enter player name:
rahul
Enter score:
4
{'dhoni': 3, 'rahul': 4}
Enter player's namesachin
player not found


# Counting letters in string taken from user & printing it in dict format

In [1]:
string = "shashank"
d = {}
for i in string:
    d[i] = d.get(i,0) + 1
print(d)  

{'s': 2, 'h': 2, 'a': 2, 'n': 1, 'k': 1}


In [8]:
d
sorted(d,key=ascii)

['a', 'h', 'k', 'n', 's']

# Sorting dict acc to keys or values using lambda function

In [29]:
colors = {0:'Red',15:'Green',20:'Blue',3:"White"}
a = sorted(colors.items(), key = lambda x:x[0]) # here x[0] means dict is sorted as per keysi.e. color code in ascending order
b = sorted(colors.items(), key = lambda x:x[1]) # here x[1] means dict is sorted as per values i.e. color name in ascending order
print(a)
print(b)

[(0, 'Red'), (3, 'White'), (15, 'Green'), (20, 'Blue')]
[(20, 'Blue'), (15, 'Green'), (0, 'Red'), (3, 'White')]


# using zip() to convert lists into dict()

In [40]:
State = ["Maharashtra",'Karnataka','Tamil Nadu','Gujarat','Delhi']
Capital_city = ['Mumbai','Bangalore','Chennai','Ahmedabad','Agra']
Tier_ii_city = ['Pune','Belgaum','Guindy','Baroda','Lajpat Nagar']
a = zip(State,Capital_city)
dict(a)

{'Maharashtra': 'Mumbai',
 'Karnataka': 'Bangalore',
 'Tamil Nadu': 'Chennai',
 'Gujarat': 'Ahmedabad',
 'Delhi': 'Agra'}

In [95]:
str1="vijay=23, Ganesh=2, Lakshmi=19, Nikhil=22"
lst_name = []
a = str1.split(",")
# b = a.split('=')
for i in a:
    b = i.split("=")
    lst_name.append(b)
d = dict(lst_name)
for k,v in d.items():
    d[k] = int(v)
print(d)

{'vijay': 23, ' Ganesh': 2, ' Lakshmi': 19, ' Nikhil': 22}


# Passing dictionary inside function

In [7]:
def dic(dictionary):
    for k,v in dictionary.items():
        print(k,'--',v)

dic({"A":1,"B":2,"C":3})

A -- 1
B -- 2
C -- 3


# Ordered Dictionary( dictionary d = {} is an unordered dict collection)

In [2]:
from collections import OrderedDict
d = OrderedDict()   # This is type of Ordered dictionary & order remains same as it is passed. 
d[10] = 'a'
d[30] = 'b'
d[40] = 'c'
d[15] = 'd'
for i,j in d.items():
    print(i,j)


10 a
30 b
40 c
15 d


# 10.Set

In [18]:
a = {'s','h','a','s','h',1,2,3,1,}
a

{1, 2, 3, 'a', 'h', 's'}

# Adding items to set

In [17]:
a = set(['a','b','c','d','e'])
a.add('f')
a

{'a', 'b', 'c', 'd', 'e', 'f'}

# Removing items from a set

In [14]:
a = set(['a','b','c','d','e'])
a.discard('a')
a

{'b', 'c', 'd', 'e'}

# Union of sets

In [30]:
a = set(['a','b','c','d','e'])
b = {'s','h','A','s','h',1,2,3,1,}
a|b

{1, 2, 3, 'A', 'a', 'b', 'c', 'd', 'e', 'h', 's'}

# Intersection of sets

In [31]:
a = set(['a',' b','c','d','e'])
b = {'s','h','A','s','h',1,2,3,1,}
a & b

set()

In [34]:
a = set(['a','b','c','d','e',1])
b = {'s','h','a','s','h',1,2,3,1,}
a & b

{1, 'a'}

# Difference of sets

In [35]:
a = set(['a','b','c','d','e',1])
b = {'s','h','a','s','h',1,2,3,1,}
a - b

{'b', 'c', 'd', 'e'}

# Compare 2 sets

In [42]:
a = set(['a',1])
b = {'s','h','a','s','h',1,2,3,1,}
a < b   # If a is a subset or superset of b it returns True else False

True

# Immutable frozenset

In [55]:
a = frozenset({'1','2','3','4','5'})
a.add('6')    # since frozenset is immutable it cannot be altered, set is mutable

AttributeError: 'frozenset' object has no attribute 'add'

# 11. Functions Part 1

In [23]:
i = int(input())
j = 1
while i > 0:
    print('* '*j)
    j += 1
    i -= 1
    if i == 0:
        break

6
* 
* * 
* * * 
* * * * 
* * * * * 
* * * * * * 


In [37]:
def sum_sub(a,b):
    sum = 0
    sub = 0
    sum += a
    sub -= b
    return sum,sub
sum_sub(5,6)

(5, -6)

In [39]:
def func(str):
    a = 'Hi'+str
    return a
func(' Shashank')

'Hi Shashank'

In [45]:
# Keyword Arguments passing

In [44]:
def grocery(a,b):
    return b,a
grocery(a='Sugar',b=50.75)

(50.75, 'Sugar')

In [52]:
def grocery(a,b=50.75):   # Default arg is b & positional arg ios a
    return b,a
print(grocery('Sugar'))
print(grocery('Sugar', b=60.23))

(50.75, 'Sugar')
(60.23, 'Sugar')


In [65]:
def grocery(a,b=50.75):   # Default arg is b & positional arg ios a
    print('a = %s' %a)
    print('b = %s' %b)
grocery('Sugar')
grocery('Sugar', b=60.23)

a = Sugar
b = 50.75
a = Sugar
b = 60.23


In [72]:
def sum_sub(a,*b):
    sum = 0; sub = 0
    for i in b:
        sum += i
        sub -= i
    return "pos arg:",a,"var arg:",sum, sub

sum_sub(5,2,3)

('pos arg:', 5, 'var arg:', 5, -5)

In [76]:
a=5
def local_func():
    a = 3
    print ("local a=",a)
local_func()
print('global a=',a)

local a= 3
global a= 5


In [3]:
a=5
def local_func():
    global a
    print ("local a=",a)
local_func()
print('global a=',a)

local a= 5
global a= 5


In [78]:
a=5
def local_func():
#     global a
    print ("local a=",a)
local_func()
print('global a=',a)

local a= 5
global a= 5


In [4]:
a = 5
def local_func():
    print ("local a=",a)
local_func()
print('global a=',a)

local a= 5
global a= 5


In [1]:
def local_func():
    global a
    print ("local a=",a)
local_func()
print('global a=',a)

NameError: name 'a' is not defined

In [2]:
def local_func():
    a = 5
    print ("local a=",a)
local_func()
print('global a=',a)

local a= 5


NameError: name 'a' is not defined

In [1]:
def outer_func():
    a = 10
    def inner_func():
        a = 20
        print("nested local inner_func a:",a)
    inner_func()
    print("local namespace of outer_func:",a)
a = 30
outer_func()
print("global namespace a:",a)

nested local inner_func a: 20
local namespace of outer_func: 10
global namespace a: 30


In [13]:
def outer_func():
    global a
    a = 10
    def inner_func():
        global a 
        a = 10
        print("nested local inner_func a:",a)
    inner_func()
    print("local namespace of outer_func:",a)
a = 30
outer_func()
print("global namespace a:",a)

nested local inner_func a: 10
local namespace of outer_func: 10
global namespace a: 10


# 12. Functions Part 2

In [34]:
def calc(*lst):
    n = len(lst)
    sum = 0; i=0
    for i in lst:
        sum += i
    avg = sum/n
    return avg, sum
calc(1,2,3,4,5)

(3.0, 15)

In [53]:
def fact(n):
    if n == 0:
        return 1 
    else:
        fac = n*fact(n-1) 
        return fac
fact(3)

6

In [54]:
a = lambda x:x**2
a(5)

25

In [62]:
a = (lambda x,y,z:(x**y)+z)
a(1,2,3)

4

In [17]:
def evn_odd(*lst):
    for i in lst:
        if i % 2 == 0:
            return True
        else:
            return False
a=list(map(lambda x:x%2,[1,2,3,4,5]))
b=list(filter(lambda x:x%2==0,[1,2,3,4,5]))
c=list(filter(lambda x:x%2,[1,2,3,4,5]))
print(a,'\t',b, '\t', c)

[1, 0, 1, 0, 1] 	 [2, 4] 	 [1, 3, 5]


In [18]:
def square(*lst):
    for i in lst:
        return i**2
def evn_odd(*lst):
    for i in lst:
        if i % 2 == 0:
            return True
        else:
            return False
a=list(filter(evn_odd,[1,2,3,4,5]))
print(list(map(square,a)))           # creating func square & than passing it in map which gets applied on each elements in a

[4, 16]


In [19]:
def evn_odd(*lst):
    for i in lst:
        if i % 2 == 0:
            return True
        else:
            return False
a=list(filter(evn_odd,[1,2,3,4,5]))
print(list(map(lambda x:x**2,a)))     # using anonymous func lambda directly 

[4, 16]


In [36]:
from functools import reduce
def evn_odd(*lst):
    for i in lst:
        if i % 2 == 0:
            return True
        else:
            return False
a=list(filter(evn_odd,[1,2,3,4,5]))
print(a)
print((reduce(lambda x,y:x*y,a))) 

[2, 4]
8


# Decorator

In [4]:
def outer_func(func):
    def inner_func():
        value = func()
        return value*2
    return inner_func

def outer_func1(func):
    def inner_func1():
        value = func()
        return value + 2
    return inner_func1

@outer_func
@outer_func1   # This inner decorator outer_func1 will be applied on below func first & than outer func decorator
def abc():
    a = 10
    return a
print(abc())

24


In [7]:
def outer_func(func):
    def inner_func():
        value = func()
        return value*2
    return inner_func

def outer_func1(func):
    def inner_func1():
        value = func()
        return value + 2
    return inner_func1


def abc():
    a = 10
    return a
result = outer_func(outer_func1(abc))
print(result())

24


# Generator object examples

In [8]:
a = []
def gen(x,y):
    while x <= y:
        yield x
        x += 1
g=gen(5,10)
print(next(g))
print(next(g))
print(next(g))
print(next(g))
print(next(g))
print(next(g))
try:
    next(g)
except:
    print("Something Wrong")   # Exception Stopiteration created as generator object exhausted which is handled by except block

for i in g:       # using for loop to iterate over generator elements from 5 to 10 stored in generator object g
    a.append(i)   # appending generator elements in list a 
print(g)
print(a)


5
6
7
8
9
10
Something Wrong
<generator object gen at 0x000002268DC31740>
[]


In [1]:
a = []
def gen(x,y):
    while x <= y:
        yield x     # yield keyword is used only once as it is used inside while loop to extract all elements 
                    # other wise it has to be used multiple times as like next()
        x += 1
g=gen(5,10)
print(next(g))   # Note: next() shall always be used single single to return only that much data which is required for processing
print(next(g))
print(next(g))
print(next(g))
print(next(g))
print(next(g))

for i in g:       # using for loop to iterate over generator elements from 5 to 10 stored in generator object g
    a.append(i)   # appending generator elements in list a 
print(g)
print(a)

5
6
7
8
9
10
<generator object gen at 0x000002268DAE6CF0>
[]


In [3]:
a = []
def gen(x,y):
    while x <= y:
        yield x
        x += 1
g=gen(5,10)
print(next(g))
print(next(g))
print(next(g))


for i in g:       # using for loop to iterate over generator elements from 5 to 10 stored in generator object g
    a.append(i)   # appending generator elements in list a 
print(type(g), g)
print(type(a),'\t',a)

5
6
7
<class 'generator'> <generator object gen at 0x000001E5CB5B0C80>
<class 'list'> 	 [8, 9, 10]


# Importing Modules 

In [89]:
import math
print(e)
pi

2.718281828459045


3.141592653589793

In [11]:
from math import e, pi
print(math.e,'\t', e , '\t', round(pi,2))  # you can write directly the attribute name or module name.attribute name

2.718281828459045 	 2.718281828459045 	 3.14


In [12]:
# importing all names
from math import *
pi

3.141592653589793

In [18]:
import sys
print(sys.path)
sys.path

['C:\\Users\\HP\\Python\\Coding Practice', 'C:\\Users\\user\\anaconda3\\python39.zip', 'C:\\Users\\user\\anaconda3\\DLLs', 'C:\\Users\\user\\anaconda3\\lib', 'C:\\Users\\user\\anaconda3', '', 'C:\\Users\\HP\\AppData\\Roaming\\Python\\Python39\\site-packages', 'C:\\Users\\user\\anaconda3\\lib\\site-packages', 'C:\\Users\\user\\anaconda3\\lib\\site-packages\\locket-0.2.1-py3.9.egg', 'C:\\Users\\user\\anaconda3\\lib\\site-packages\\win32', 'C:\\Users\\user\\anaconda3\\lib\\site-packages\\win32\\lib', 'C:\\Users\\user\\anaconda3\\lib\\site-packages\\Pythonwin', 'C:\\Users\\user\\anaconda3\\lib\\site-packages\\IPython\\extensions', 'C:\\Users\\HP\\.ipython']


['C:\\Users\\HP\\Python\\Coding Practice',
 'C:\\Users\\user\\anaconda3\\python39.zip',
 'C:\\Users\\user\\anaconda3\\DLLs',
 'C:\\Users\\user\\anaconda3\\lib',
 'C:\\Users\\user\\anaconda3',
 '',
 'C:\\Users\\HP\\AppData\\Roaming\\Python\\Python39\\site-packages',
 'C:\\Users\\user\\anaconda3\\lib\\site-packages',
 'C:\\Users\\user\\anaconda3\\lib\\site-packages\\locket-0.2.1-py3.9.egg',
 'C:\\Users\\user\\anaconda3\\lib\\site-packages\\win32',
 'C:\\Users\\user\\anaconda3\\lib\\site-packages\\win32\\lib',
 'C:\\Users\\user\\anaconda3\\lib\\site-packages\\Pythonwin',
 'C:\\Users\\user\\anaconda3\\lib\\site-packages\\IPython\\extensions',
 'C:\\Users\\HP\\.ipython']

In [71]:
from my_math import my_add, my_prod, my_mul
print(my_prod(5,2))
my_add(5,2)

25


7

In [1]:
import my_math
import imp
imp.reload(my_math)   # reload func needs to be imported from imp module if there are any changes made in the existing module
import my_math        # After reload func only we can use my_math again
print()
import my_math  

This code run as a module
This code run as a module



In [76]:
import my_math
imp.reload(my_math)

Hello my_math got executed


<module 'my_math' from 'C:\\Users\\HP\\Python\\Coding Practice\\my_math.py'>

In [86]:
my_math.__name__

'my_math'

In [96]:
import my_math
imp.reload(my_math)  #if any changes made in a module imp.reload(module name) needs to be done before accessing any func attribute from that module
my_math.func()

This code run as a module
my_math
Hello I m executing


# 13. File Handling

#Program to input any content dynamically & write it into text file

In [13]:
f = open('my_file.txt', 'w')
str = input("Enter lines to insert into text file:")
f.write(str)
f.close()

Enter lines to insert into text file:Hello Python is very easy


#Reading content from my_file.txt & printing it on monitor

In [14]:
f = open('my_file.txt')  # by default mode is set to read mode
str = f.read(7)
str1 = f.read()

print(str)
print(str1)
f.close()

Hello P
ython is very easy


#Pgm to write multiple lines in a text file by accepting inputs from user

In [4]:
f = open('my_file.txt', 'w')
print("Enter your content >>> END is to stop execution:")
while str != 'END':
    str = input()
    f.write(str + '\n')
f.close()

Enter your content >>> END is to stop execution:
this is line 1
this is line 2
---
@
END


#Reading contents from a text file 

In [5]:
f = open('my_file.txt') # by default mode is read mode
str = f.read()
str1 = f.readlines()
print(str)
print(str1)

this is line 1
this is line 2
---
@
END

[]


In [6]:
f = open('my_file.txt')
str1 = f.readlines()    # readlines will print o/p in form of list alongwith escape seq char '\n'
print(str1)

['this is line 1\n', 'this is line 2\n', '---\n', '@\n', 'END\n']


In [7]:
'''suppressing escape seq char \n'''

f = open('my_file.txt')
str1 = f.read().splitlines()    # read().splitlines() will print o/p in form of list removing unwanted escape seq char '\n'
print(str1)
f.close()

['this is line 1', 'this is line 2', '---', '@', 'END']


#Accepting file name as i/p from user & if file found in current working directory appending file with our new lines

In [9]:
import os
os.getcwd()

input("Enter file name to search:")
if os.path.isfile('my_file.txt'):
    print('my_file.txt exists')
    f = open('my_file.txt','a+')
    str = f.write('I have appended this file')
    f.close()
    f = open('my_file.txt')
    str1 = f.read()
    print(str1)
else:
    print('my_file does not exist')
f.close()

Enter file name to search:my_file.txt
my_file.txt exists
this is line 1
this is line 2
---
@
END
I have appended this file


In [ ]:
# Below code was run after closing the opened file my_file.txt & deleting it from current directory so the o/p i shown accordingly

In [2]:
import os
os.getcwd()

input("Enter file name to search:")
if os.path.isfile('my_file.txt'):
    print('my_file.txt exists')
    f = open('my_file.txt','a+')
#     str = f.write('I have appended this file')
    f.close()
    f = open('my_file.txt')
    str1 = f.read()
    print(str1)
else:
    print('my_file does not exist')
f.close()

Enter file name to search:my_file.txt
my_file does not exist


#Code to copy an image(binary file) into another binary file 

In [18]:
with open('abdulkalam.jfif','rb') as f1:
    img = f1.read()
with open('new.jpg','wb') as f2:
    f2.write(img)

In [15]:
with open('file.txt','w+b') as f2:
    f2.write(b'File Handling Practice')
    print(f2.tell())
    f2.seek(6,0)       # 0 indicates read from the beginning of the file all contents after pointer set at 6th position
    print(f2.read())

22
b'andling Practice'


In [22]:
with open('file.txt','w+b') as f2:
    f2.write(b'File Handling Practice')
    print(f2.tell())
    f2.seek(20)     # Current pointer position set to 20th i.e at i of practice
# This will read letters from 20th cursor position in the reverse order as - sign is used upto 11th pointer position 
# & 1 indicates current pointer position  
    f2.seek(-11,1)    
    print(f2.read())

22
b'ling Practice'


In [25]:
with open('file.txt','w+b') as f2:
    f2.write(b'File Handling Practice')
    print(f2.tell())
    f2.seek(20)     # Current pointer position set to 20th i.e at i of practice
# This will read letters from the end in the reverse order as - sign is used upto 11th pointer position 
# & 2 indicates read from end even though pointer was set to 20th position it will start reading right from the end  
    f2.seek(-11,2)    
    print(f2.read())

22
b'ng Practice'


In [8]:
with open('file.txt','w+b') as f2:
    str = 'This is line 2'
    f2.write(b'This is line 1') #  b'ajnd' is used when directly string literal is passed without assigning it to a variable 
    f2.write(b'\n')
    f2.write(str.encode())      # .encode() method used when any string variable is to be converted into binary format

In [7]:
# similarly when str is to be read we need to used str.decode 

In [2]:
with open('file.txt','r+b') as f2:
    str = f2.readline()   # readline is used to print each line by line o/p
#     str1 = f2.read()
    print(str.decode())
#     print(str1.decode())

This is line 1



In [28]:
reclen = 20
with open("cities.bin", 'w+b') as f:
    n = int(input("How many entries:"))
    for i in range(n):
        city = input("Enter city name:")
        city = city + (reclen-len(city)) * ''
        f.write(city.encode())
        f.write(b'\n') 

How many entries:3
Enter city name:mumbai
Enter city name:pune
Enter city name:chennai


In [ ]:
with open("cities.bin", 'rb') as f:
    reclen = 20
    n = int(input("How many entries:"))    
    f.seek(reclen * (n-1))
    str = f.read(reclen)
    print("Your selected city:",str.decode())

In [28]:
f = open('my_file.bin', 'w+b')
n = int(input("How many entries:"))
for i in range(n):
    str = input("Enter lines to insert into text file:")
    ln = len(str)
    str = str + (20-ln) * ''
    f.write(str.encode())
    f.write(b'\n')
f.close()

with open('my_file.bin','r+b') as f1:
    n = int(input("Enter rec num:"))
    f1.seek(0)
    var = f1.seek(20 * (n-1))
    print(f1.tell())
    str1 = f1.read(20 * (n-1))
    print(str1.decode())
# f.close()

How many entries:3
Enter lines to insert into text file:mum
Enter lines to insert into text file:pune
Enter lines to insert into text file:hyd
Enter rec num:2
20



In [5]:
f = open('my_file.bin', 'rb')
n = int(input("Enter rec num:"))
var = f.seek(20 * (n-1))
str1 = f.read(var)
print(str1.decode())
f.close()

Enter rec num:1



In [ ]:
# Python progrsm to create phone book with names & phone nos.

In [1]:
with open('Phonebook.dat', 'wb') as f:
    n = int(input("How many entries:"))
    for i in range(n):
        name = input("Enter name:")
        phone = input("Enter number:")
        name = name.encode()
        phone = phone.encode()
        f.write(name+b' '+phone)

How many entries:3
Enter name:Shashank
Enter number:9860855475
Enter name:Pappa
Enter number:9029517025
Enter name:Mummy
Enter number:7350517195


In [8]:
import mmap, sys
print("1 to display all the entries")
print("2 to display phone number")
print("3 to modify an entry")
print("4 exit")
ch = input("Enter your choice:")
if ch == '4':
    try:
        sys.exit()
    except:
        print("System Exit")
with open('Phonebook.dat', 'r+b') as f:
    mm = mmap.mmap(f.fileno(),0)
    if ch =='1':
        print(mm.read().decode())
    if ch == '2':
        name = input("Enter name:")
        n = mm.find(name.encode())
        n1 = n +len(name)   # To start after correspondong name as we need only phone num & not name
        ph = mm[n1:n1+11]   # To start from phone num & end with 10 digits of phone num
        print("Phone no.",ph.decode())
    if ch == '3':
        name = input("Enter name:")
        n = mm.find(name.encode())
        n1 = n +len(name) 
        ph1 = input("Enter new num:")
        mm[n1:n1+11]  = ph1.encode()

1 to display all the entries
2 to display phone number
3 to modify an entry
4 exit
Enter your choice:1
Shashank 9158122006Pappa 9029517025Mummy 7350517195


# 14.Exception Handling

In [5]:
try:
    f = open('division.bin', "w+b")
    a,b = (int(x) for x in input("Enter 2 numbers:").split())
    c = round(a/b, 1)
    c = str(c)
    c = c.encode()
    f.write(c)
    f.seek(0)
    str1 = f.read()
    print("Value of Division is:",str1.decode())
    print("Current cursor position:",f.tell())
    
except ZeroDivisionError:
    print("Division by zero not possible")
    
finally:
    f.close()
    print("File closed")

Enter 2 numbers:444 22
Value of Division is: 20.2
Current cursor position: 4
File closed


In [9]:
assert 10 > 1

In [10]:
assert 10 < 1   # AssertionError raised when assert statement raises an error

AssertionError: 

In [ ]:
# SyntaxError

In [2]:
try:
    print("Accepted Date Format is: YYYY,M,D format")
    date = eval(input("Enter Date:"))  #eval() func takes list,tuple or dict as input & evaluates it & displays the o/p 
except SyntaxError:
    print("Invalid Date Entered")
else:
    print("Date Entered is:",date)

Accepted Date Format is: YYYY,M,D format
Enter Date:2016,01,02
Invalid Date Entered


In [ ]:
#AssertionError

In [23]:
try:
    x = int(input("Enter num between 5 & 10:"))
    assert x>=5 and x<=10 
    print("The num entered is",x)
except AssertionError:
    print("Value of x not in range of 5 ~ 10")

Enter num between 5 & 10:6
The num entered is 6


In [ ]:
# AssertionError if occurred due to faulty assert statement customise assert statement msg appears 

In [20]:
try:
    x = int(input("Enter num between 5 & 10:"))
    assert x <= 5 and x >= 10, "Value of x not in range of 5 ~ 10"
    print("The num entered is",x)
except AssertionError as e:
    print(e)

Enter num between 5 & 10:11
Value of x not in range of 5 ~ 10


In [2]:
import logging
logging.basicConfig(filename = 'ErrLog.txt', level = logging.ERROR)
logging.critical("There is a design problem in program")
logging.error("There is an Err in program")
logging.warning("The program is going slow")
logging.info("You are a Junior Programmer")
logging.debug("Line 10 contains syntax error")

In [7]:
import logging
logging.basicConfig(filename='logs.txt', level = logging.INFO)

'''To write our code'''
try:
    a = int(input("Enter first num:"))
    b = int(input("Enter second num:"))
    c = a/b
    
# To handle if any exceptions occurred
except Exception as e:
    logging.exception(e)

except ZeroDivisionError as e:
    logging.exception(e)
    logging.warning("Division by Zero occurred")
      
# To print the o/p
else:
    print("The result of division:", c)

Enter first num:5
Enter second num:0


# 15.Regular Expressions

#search, match, findall, split, sub

In [9]:
str = 'This is raw\nstring'
print(str)

This is raw
string


In [10]:
str = r'This is raw\nstring'   #becoz of raw str \n becomes \\n so raw & string gets continued in same line
# above line withour r' ' can also be written as 'This is raw\\nstring'
print(str)

This is raw\nstring


In [21]:
import re
prog = re.compile(r'm\w+')
str = 'm cat mat rat bat'
result = prog.search(str)
print(result.group())

mat


In [26]:
import re 
str = 'man sun mop run'
result = re.search(r'm\w+', str)   #use of search alongwith group method
print(result.group())

man


In [29]:
import re 
str = 'man sun mop run'
result = re.match(r'm\w+', str)  #use of match alongwith group method
print(result.group())

man


In [25]:
import re 
str = 'man sun mop run'
result = re.findall(r'm\w+', str)  #use of findall method
print(result)

['man', 'mop']


In [38]:
import re 
str = 'man; sun.mop:run'
result = re.split(r'\W+', str)  #use of split method. W splits at non alphanumeric letters vice versa of small w 
print(result)

['man', 'sun', 'mop', 'run']


In [43]:
# Use case syntax >>> sub(regular expression, new string, string) 
import re 
str = 'You are a new programmer'
result = re.sub(r'new','intermediate', str)  #use of sub method to replace any word or list of words
print(result)

You are a intermediate programmer


In [49]:
import re 
str = 'An apple a day keeps doctor away '
result = re.findall(r'[A,a]\w*', str)  #use of findall method
print(result)

['An', 'apple', 'a', 'ay', 'away']


In [ ]:
#retrieve words starting with a

In [61]:
import re 
str = 'An apple a day keeps doctor away '
result = re.findall(r'\ba\w*', str)  #use of findall method
for i in result:   # Using for loop to iterate over a list of words starting with 'a' which is stored in result
    print(i)

apple
a
away


In [ ]:
#retrieve all words starting with numeric digit

In [4]:
import re
str = 'The meeting will be conducted on 1st & 2nd of every month'
result1 = re.findall(r'\d+', str)
result2 = re.findall(r'\d\w+', str)
print(result1)
print(result2)

['1', '2']
['1st', '2nd']


In [ ]:
#to retrieve all words having 5 char length

In [12]:
import re
str = 'one two three four five six seven eight nine ten'
res = re.findall(r'\b\w{5}\b',str)
res

['three', 'seven', 'eight']

In [ ]:
#to retrieve all words having atleast 4 char length

In [14]:
import re
str = 'one two three four five six seven eight nine ten'
res = re.findall(r'\b\w{4,}\b',str)
res

['three', 'four', 'five', 'seven', 'eight', 'nine']

In [ ]:
#to retrieve all words having atleast 4 & max 5 char length

In [18]:
import re
str = 'one two three four five six seven eight nine ten'
res = re.findall(r'\b\w{4,5}\b',str)
res

['three', 'four', 'five', 'seven', 'eight', 'nine']

In [ ]:
#to retrieve single digit nos.

In [19]:
import re
str = 'one two three four 5 6 7 8 9 10 1 0'
res = re.findall(r'\b\d\b',str)
res

['5', '6', '7', '8', '9', '1', '0']

In [ ]:
#to retrieve double digit nos.

In [21]:
import re
str = 'one two three four 5 6 7 8 9 10 1 0'
res = re.findall(r'\b\d\d\b',str)
res

['10']

In [ ]:
#to retrieve 'one' present at start of str

In [30]:
import re
str = 'one two three four 5 6 7 8 9 10 1 0 ONE'
res = re.findall(r'\Ao\w+',str)
res

['one']

In [ ]:
#to retrieve 'ONE' present at end of str

In [34]:
import re
str = 'one two three four 5 6 7 8 9 10 1 0 ONE'
res = re.findall(r'O\w+\Z',str)
res

['ONE']

In [ ]:
#to retrieve phone number

In [42]:
import re
str = 'Shashank:9860855475'
res = re.findall(r'\d+',str)
res

['9860855475']

In [ ]:
#to find all words starting withg an or ak

In [58]:
import re
str = 'anil akshat akhil anant akshay ashok ajay'
res = re.findall(r'a[n,k]\w+',str)
res

['anil', 'akshat', 'akhil', 'anant', 'akshay']

In [ ]:
#to retrieve D.O.B from a str

In [26]:
import re
str = 'anil 1 20-01-2018, akhil 2 01-12-2000, anant 3 2-3-1993 Jack 4'
res = re.findall(r'\b\d*-\d*-\d{4}\b',str)
res

['20-01-2018', '01-12-2000', '2-3-1993']

In [ ]:
#to search word at the end of the str

In [37]:
import re
str = 'Hello world'
res = re.findall(r'[W]orld\Z',str)
res

[]

In [38]:
import re
str = 'Hello world'
res = re.findall(r'[Ww]orld\Z',str)
res

['world']

In [41]:
import re
str = 'Hello world'
res = re.findall(r'[W]orld\Z', str, re.I)  #re.I indicates Ignorecase
res

['world']

In [51]:
#To retrieve DOB & names in a separate list

In [1]:
import re
str = 'anil 1 20-01-2018, akhil 2 01-12-2000, anant 3 2-3-1993'
res = re.findall(r'\d*-\d*-\d{4}',str)
print(res)
res1 = re.findall(r'\w+\s\d{1}',str)   #\s represents white space
print(res1)

['20-01-2018', '01-12-2000', '2-3-1993']
['anil 1', 'akhil 2', 'anant 3']


# 16.Numpy

In [1]:
import numpy as np

In [ ]:
#To show the execution time with numpy & python list comprehension technique

In [35]:
arr = np.arange(10000)
lst = [arr]

In [50]:
%time for i in range(10): arr*2

Wall time: 1.98 ms


In [51]:
%time for i in range(10): [x*2 for x in lst]

Wall time: 2 ms


In [9]:
#Generates some random values
array = np.random.randn(2,3)
array

array([[ 0.7231711 ,  0.89887556,  0.14359014],
       [-1.28732661,  0.1064898 , -2.26924885]])

In [28]:
#Its not safe to assume that .empty() attribute will always return arr of zeros.It may return sometimes garbage values

np.empty((2,3,2)) #2 matrices x 3 rows x 2 col

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [32]:
np.full((5,5),3.1, np.int)

C:\Users\HP\AppData\Local\Temp/ipykernel_8/2065556550.py:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np.full((5,5),3.1, np.int)


array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [44]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [45]:
np.identity(4, np.bool)

C:\Users\HP\AppData\Local\Temp/ipykernel_8/4049952196.py:1: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np.identity(4, np.bool)


array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False],
       [False, False, False,  True]])

In [48]:
np.eye(4, dtype=np.int)  

C:\Users\HP\AppData\Local\Temp/ipykernel_8/75362207.py:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np.eye(4, dtype=np.int)


array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [52]:
np.eye(3,2)

array([[1., 0.],
       [0., 1.],
       [0., 0.]])

In [55]:
np.eye(3,1,3)  # .eye() & .identity() returns same value

array([[0.],
       [0.],
       [0.]])

In [62]:
np.ones(3)

array([1., 1., 1.])

In [63]:
np.ones(3)*(5-2)

array([3., 3., 3.])

In [80]:
#to set manually any values on diagonal axis elements

np.diag([3,2,1])

array([[3, 0, 0],
       [0, 2, 0],
       [0, 0, 1]])

In [69]:
#fromfunction()

# i & j will take the rows & col indices values & lambda func applied i-j resulting in 3x3 matrix
np.fromfunction(lambda i,j:i-j, (3,3)) 

array([[ 0., -1., -2.],
       [ 1.,  0., -1.],
       [ 2.,  1.,  0.]])

In [71]:
np.fromfunction(lambda i,j:i==j, (3,3)) #to get boolean values

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [92]:
np.full(8,5)   #.full() will return 8 values row with '5' as a value

array([5, 5, 5, 5, 5, 5, 5, 5])

In [29]:
import numpy as np
from scipy.stats import skew, skewtest
x = np.random.normal(0, 2, 50) # create random values based on a normal distribution
print(x)
print(skew(x))
print(skew(x, axis=0))
var = (skew([1,2,-1,0,5,8,0,1,-5,6,4,3,9]))
print(var)

#The function `skewtest` can be used to determine if the skewness value is close enough to zero

if skewtest(x):             # This shows if skewness value of x is close enough to zero is true below statement printed                
    print("Value is Close enough to zero")

[-2.32214197 -2.97435184  2.94633917  2.47117083 -1.10110532  3.19145797
 -1.33559636  0.04258742 -2.46950127 -0.19056731  1.58198088  3.97763885
 -1.65481591  2.17288761 -0.15470569 -0.03907148  1.15384107 -1.51833069
 -1.3682585  -1.77189957  1.15912291  1.1701476   3.18066642  0.44944434
  2.80434133  2.59804741  2.65825331  1.98449749 -0.94479968 -1.11207759
 -0.47808974  3.56477449 -4.56531728 -1.65510192  0.08374971 -1.52494991
  0.07773956 -0.55466545 -0.3341295  -1.28513898 -0.26235974 -0.51029733
  1.43028969  0.5848373   3.05036656  0.57783235 -2.97314223 -0.74107909
 -3.94283137 -0.64552786]
0.015043044485939837
0.015043044485939837
-0.030888436975059594
Value is Close enough to zero
