In [9]:
# .pop() method used to remove & return the last element in the list by default

In [9]:
a = input("Enter any str: ")   #bool if is empty than it returns first non zero value else it returns second value
['f', 't'][bool(a)]

Enter any str: h


't'

In [6]:
a = input("Enter any str :")
['f', 't'][bool(a)]

Enter any str :


'f'

# To access only docstring from program

#NOTE: Func docstr are placed in immediate line after func header as shown in below code

In [1]:
def fun_docs():
    """I know how to interact with the docstrings of a function."""  
    
    return None

fun_docs.__doc__    # This .__doc__ method used rather than func calling

'I know how to interact with the docstrings of a function.'

# To find max of a number

In [1]:
def foo(fname, val):
    print(fname(val))
foo(max, val = input().split())

1 0 -1
1


# To find Factorial of a given num (Recursion method)

In [13]:
a=int(input("Enter a num:"))
factorial = 1
for i in range(1,(a+1)):
    factorial=factorial*i
print(factorial,end=' ')

Enter a num:5
120 

In [11]:
# Alternate code (Recursion method)

In [12]:
def factorial():
    fact = (1)
    num = int(input("Enter a num:"))
    if num < 0:
        print("Factorial not posssible")
    elif num == 0:
        print("Factorial of 0 is 1")
    else:
        for i in range(1,num+1):
            fact = fact*i        # Crucial line Code for finding factorial
    return float(round(fact,1))
factorial()

Enter a num:5


120.0

In [5]:
from math import factorial
print(factorial(5))             # imported identifier factorial can't be used with module name as math.factorial

120


# To print Even & Odd List separately

In [94]:
a=[10,11,12,13,14,15]
b = [];c=[]
for i in a:
    if i % 2 == 0:
        b.append(i)
    else:
        c.append(i)  
        
print("Even list",b)
print("Odd list",c)

Even list [10, 12, 14]
Odd list [11, 13, 15]


# Python Program to Merge Two Lists and Sort it

In [3]:
a=[1,2,3,4,5,6,7,8,9,10]

aeven=list(range(2,10,2))
aodd=list(range(1,10,2))
anew=aeven+aodd
print(anew)
anew.sort()
print(anew)

[2, 4, 6, 8, 1, 3, 5, 7, 9]
[1, 2, 3, 4, 5, 6, 7, 8, 9]


In [1]:
help(list)

Help on class list in module builtins:

class list(object)
 |  list(iterable=(), /)
 |  
 |  Built-in mutable sequence.
 |  
 |  If no argument is given, the constructor creates a new empty list.
 |  The argument must be an iterable if specified.
 |  
 |  Methods defined here:
 |  
 |  __add__(self, value, /)
 |      Return self+value.
 |  
 |  __contains__(self, key, /)
 |      Return key in self.
 |  
 |  __delitem__(self, key, /)
 |      Delete self[key].
 |  
 |  __eq__(self, value, /)
 |      Return self==value.
 |  
 |  __ge__(self, value, /)
 |      Return self>=value.
 |  
 |  __getattribute__(self, name, /)
 |      Return getattr(self, name).
 |  
 |  __getitem__(...)
 |      x.__getitem__(y) <==> x[y]
 |  
 |  __gt__(self, value, /)
 |      Return self>value.
 |  
 |  __iadd__(self, value, /)
 |      Implement self+=value.
 |  
 |  __imul__(self, value, /)
 |      Implement self*=value.
 |  
 |  __init__(self, /, *args, **kwargs)
 |      Initialize self.  See help(type(self))

In [69]:
a=[1,2,3,4,5,6,7,8,9,10]
print(a.pop()-1)


9


# To find separate even & odd list

In [8]:

a=[1,2,5,95,86,30,38,41]
b=[]
c=[]
for i in a:
    if (i%2==0):
        (b.append(i))
    else:
        (c.append(i))
print("Even series:",b)
print("Odd series:",c)  

Even series: [2, 86, 30, 38]
Odd series: [1, 5, 95, 41]


# To find even & odd numbers

In [10]:
#code to find even & odd number
a=int(input("Enter number:"))
if (a%2 ==0):
    print("Num is even")
else:
    print("num is odd")

Enter number:2
Num is even


# To find union & intersection in set

In [49]:
a={1,2,3}
b={3,4,5}

c=a.union(b)
d=a.intersection(b)
print(c)
print(d)
e=[c]
type(c)

{1, 2, 3, 4, 5}
{3}


set

In [2]:
dir(tuple)

['__add__',
 '__class__',
 '__class_getitem__',
 '__contains__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getnewargs__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rmul__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'count',
 'index']

# To find sqrt of int & float

In [21]:
a=float(input("Enter a number:"))

b=a**0.5
print(b)

Enter a number:24.3
4.929503017546495


# To find sqrt of complex nos.

In [16]:
import cmath
a=eval(input("Enter a number:"))
b=cmath.sqrt(a)
print(b)

Enter a number:5+4j
(2.3877944046161983+0.8375930507808814j)


# To find area of triangle

In [28]:
base=float(input("enter base:"))
height=float(input("enter perpendicular height:"))
area=base*height*0.5
print("area of triangle for {} base and {} height:".format(base,height),area)

enter base:24
enter perpendicular height:12
area of triangle for 24.0 base and 12.0 height: 144.0


# To solve quadratic equation

In [4]:
import cmath
a=1
b=5
c=6
d=(b**2) -(4*a*c)
e=cmath.sqrt(d) #inbuilt .sqrt() method of package cmath is used to solve complex quadratic equation
sol1=(-b+e)/(2*a)
sol2=(-b-e)/(2*a)
print(sol1)
print(sol2)

(-2+0j)
(-3+0j)


# To swap 2 variables

In [6]:
a=5
b=10
print(a,b)
a,b=b,a
print(a,b)

5 10
10 5


# Program to reverse a given number

In [8]:
x = '64'
y = x[1]+x[0]
print(int(x))
print(int(y))

64
46


# To find sum of all nos.

In [3]:
a=[1,2,3,4,5,6,7,8,9]
i = 0
b = 0
while i <= len(a):
    b += a[i]
    i += 1
    if i == len(a):
        break
print("Sum of all nos. in a:",b)

Sum of all nos. in a: 45


# To find intersection of 2 lists

In [4]:
a={'s','h','a','s','h','a','n','k'}
b={'n','k'}
c=set('z')   # This type of set() function can contain only 1 arg
d=a.intersection(b)
e=a.intersection(c)   
print(list(d))
print(list(e))

['k', 'n']
[]


# To find positive numbers in a list using list comprehension

In [23]:
a=[-1,2,0,-2,-4]
[i for i in a if i >= 0]

[2, 0]

# To convert all numbers into positive (absolute) numbers

In [2]:
a=[-1,2,0,-2,-4]
[abs(i) for i in a]

[1, 2, 0, 2, 4]

#                                                    String Codes

# Reverse of a given Str

In [43]:
i = len(a)
a = "This is learnbay"
b = ''

while i <= len(a):
    b += a[i-1]
    i -= 1
    if i == 0:
        break
print(f"Reverse of str {a} is:",b)  

Reverse of str This is learnbay is: yabnrael si sihT


# Palindrome of a Str

In [44]:
def is_palindrome(s):
    if s == s[::-1]:
        return f"{s} is a palindrome"
    else:
        return f"{s} Not a palindrome"
print(is_palindrome('Wow'))
print(is_palindrome('wow'))
print(is_palindrome('cat'))

Wow Not a palindrome
wow is a palindrome
cat Not a palindrome


# Replace a with $ in a given Str

In [45]:
a="This is Shashank Sadadekar"
b = ''
for i in range(len(a)): #i will iterate over len(a) so 'i' will take index values as 0,1,2... for given str a
    if a[i] == 'a':
        b=a.replace('a','$')
print(b)

This is Sh$sh$nk S$d$dek$r


In [ ]:
# Alternate method

In [133]:
a="This is Shashank Sadadekar"
b = ''                    # Always use empty variable of same data(object) type for saving new changes made in original variable
for i in a:               #i will iterate over str(a) so 'i' will take index values as T,h,i,s,'''i''s'... for given str a
    if i == 'a':
        b=a.replace('a','$')
print(b)

This is Sh$sh$nk S$d$dek$r


# Count vowels in a Str

In [6]:
a="This is Shashank Sadadekar"
b = a.lower()
c =''
d = 0
for i in b:
    if (i== 'a' or i=='e'or i=='i'or i=='o'or i=='u'):
        c += i
        d += 1
e = {c,d}
print(e)
print(type(e))

{8, 'iiaaaaea'}
<class 'set'>


# To find largest Str without using inbuilt func

In [48]:
a = " This is Python      "    # Spaces are also calculated & counter incremented by 1
b = 'My name is Shashank'
count1 = count2 = 0
for i in a:
    count1+=1
for j in b:
    count2+=1
if count1 > count2:
    print('Str a is larger')
else:
    print('Str b is larger')

Str a is larger


# To count number of digits & letters in a Str

In [1]:
a=input("Enter any string:")
d = int()
e = int()
f = int()
for i in a:
    if i.isalpha():
        d += 1
    elif i.isdigit():
        e += 1
    elif i.isspace():
        continue
    elif i.isascii():
        f += 1
print("letters:",d,end=' ')
print("digits:",e,end=' ')
print("special:",f)

Enter any string:hello   world!123@
letters: 10 digits: 3 special: 2


# To count number of lowercase letters in a Str

In [66]:
a="ShasHanK"
b = a.lower()
count_lower = 0
# for i in range(len(a)):
#     for j in range(len(b)): 
#         if a == b:
#             d += 1 
#         else:
#             e += 1
for i in range(len(a)):
    if a[i] == b[i]:
        count_lower += 1
print("Lowercase count is:",count_lower)

Lowercase count is: 5


# Count occurrences of sub str in a given Str

In [67]:
a='Learnbay'
b='Learnbay is an excellent firm'
b.__contains__(a)

True

In [68]:
a='Learnbay'
b='Learnbay is an excellent firm'
d = 0
if a in b:
    d += 1
print(f"Occurrences of word {a} is:",d)
            

Occurrences of word Learnbay is: 1


# Lists & Tuples codes

# To swap first & last elements in a list

In [25]:
a=['this', 'is', 'a', 'learnbay','class']
a[0],a[4]=a[4],a[0]
print(a)

['class', 'is', 'a', 'learnbay', 'this']


# To sort a list acc to len of elements

In [26]:
a=['this', 'is', 'a', 'learnbay','class']
b=''  
a.sort(key=len)
print(a)

['a', 'is', 'this', 'class', 'learnbay']


# to find largest number

In [74]:

a=input("Enter value1:")
b=input("Enter value2:")
c=input("Enter value3:")
if(a>=b and a>=c):
    print("a is largest")
elif b>=a and b>=c:
    print("b is largest")
else:
    print("c is largest")

Enter value1:-1
Enter value2:0
Enter value3:-2
b is largest


# Count of Even & Odd Numbers

In [77]:
a=[1,2,3,4,5,6,7,8,9]
even = 0
odd = 0
for i in a:
    if i % 2 == 0:
        even += 1
    else:
        odd += 1
print("Count of Even:",even,'\t',"Count of Odd",odd)

Count of Even: 4 	 Count of Odd 5


# Put Even & Odd in a separate list

In [78]:
#Python Program to Put Even and Odd elements in a List into Two Different Lists

a=[1,2,3,4,5,6,7,8,9,10]
print("My Even List:"+str(list(range(0,10,2))))
print("My Odd List:"+str(list(range(1,10,2))))
aeven=list(range(0,10,2))
aodd=list(range(1,10,2))
anew=aeven+aodd
print(anew)

My Even List:[0, 2, 4, 6, 8]
My Odd List:[1, 3, 5, 7, 9]
[0, 2, 4, 6, 8, 1, 3, 5, 7, 9]


# Read list of words & return longest element

In [115]:
a='Learnbay is an excellent firm'
b = a.split(" ")

word_len=len(b[0])
word =b[0]

for i in b:
    if (len(i)>word_len):
        word=i

print("The word with the longest length is :",word)

The word with the longest length is : excellent


# To find list of tuples with first element & second as square of first element

In [128]:
a=float(input("Enter any number:"))
b=a**2
print(a,b)
type((a,b))

Enter any number:5
5.0 25.0


tuple

# to remove duplicates using set() function method for a given list of elements

In [129]:
a1=[19, 19, 19, 18, 18, 18, 17, 14, 13, 12, 11, 10, 8, 7, 6, 6, 3, 2, 2, 1]
b1=set(a1)
b1=list(b1) #Type casting to list from set
print(b1)

[1, 2, 3, 6, 7, 8, 10, 11, 12, 13, 14, 17, 18, 19]


# To remove duplicates using List(or Loop) comprehension method

In [130]:
a1=[19, 19, 19, 18, 18, 18, 17, 14, 13, 12, 11, 10, 8, 7, 6, 6, 3, 2, 2, 1]
b1=[]
[b1.append(i) for i in a1 if i not in b1]
print(type(b1))
print(b1)

<class 'list'>
[19, 18, 17, 14, 13, 12, 11, 10, 8, 7, 6, 3, 2, 1]


# To remove duplicates using for loop & if condition (naive method)

In [131]:
a=[18, 7, 6, 1, 19, 6, 17, 3, 8, 2, 2, 19, 18, 13, 14, 10, 11, 18, 12, 19]
a.sort(reverse=True)

a1=[19, 19, 19, 18, 18, 18, 17, 14, 13, 12, 11, 10, 8, 7, 6, 6, 3, 2, 2, 1]

b1=[]

for i in a1:
    if  i not in b1:
        (b1.append(i))
print(b1)        

[19, 18, 17, 14, 13, 12, 11, 10, 8, 7, 6, 3, 2, 1]


# Dictionary Codes

# To find if a given key exists in a dict or not

In [14]:
a = float(input("Enter a key"))
b = {1:"A",2:"B",3:"C",4:'D',5:"E"}
if a not in b.keys():
    print("incorrect value entered")
elif a in b.keys():
    print('key found')

Enter a key5
key found


# To remove any given key from dict

In [19]:
a = float(input("Enter a key"))
b = {1:"A",2:"B",3:"C",4:'D',5:"E"}
b.pop(a)
print(b)

Enter a key3
{1: 'A', 2: 'B', 4: 'D', 5: 'E'}


# To sort dict as per keys

In [35]:
a = [2,4,1,5,3]
b = ['A','B','C','D',"E"]
print("Dict before Sorting:",dict( zip(a,b) ) )
a.sort()      
print("Dict After Sorting:",dict( zip(a,b) ) )

Dict before Sorting: {2: 'A', 4: 'B', 1: 'C', 5: 'D', 3: 'E'}
Dict After Sorting: {1: 'A', 2: 'B', 3: 'C', 4: 'D', 5: 'E'}


# To iterate over dict using for loops

In [46]:
a = {1:"A",2:"B",3:"C",4:'D',5:"E"}
for k,v in a.items():
    print(f"{k} is key of value {v}")

1 is key of value A
2 is key of value B
3 is key of value C
4 is key of value D
5 is key of value E


# To sum all the items in a dict

In [52]:
a = {'1':"A",'2':"B",'3':"C",'4':'D','5':"E"}
for k,v in a.items():
    print(k+' '+v)

1 A
2 B
3 C
4 D
5 E


# To sum all the items in a dict

In [60]:
a = {'1':10,'2':11,'3':12,'4':13,'5':14}
for k,v in a.items():
    pass
print(sum(a.values()))

60


# To add elements in a dict

In [14]:
a={1:5,2:21,2:6,3:8,4:0}
b={'S':1,'h':2,'a':3,'s':4,'h':5,'a':6,'n':7,'k':8}
a.update(b)
print(a)

{1: 5, 2: 6, 3: 8, 4: 0, 'S': 1, 'h': 5, 'a': 6, 's': 4, 'n': 7, 'k': 8}


In [17]:
# Alternate method

In [16]:
a={1:5,2:21,2:6,3:8,4:0}
b={'S':1,'h':2,'a':3,'s':4,'h':5,'a':6,'n':7,'k':8}
c = a|b
print(c)

{1: 5, 2: 6, 3: 8, 4: 0, 'S': 1, 'h': 5, 'a': 6, 's': 4, 'n': 7, 'k': 8}


# To delete keys & values from dict

In [18]:
a={1:5,2:21,2:6,3:8,4:0} #If keys same with different values the later key:value pair is printed
del a[1]
print(a)

{2: 6, 3: 8, 4: 0}


# Use of .items() method 

In [19]:
a={1:5,2:21,2:6,3:8,4:0}
b=a.items()
print(b)

dict_items([(1, 5), (2, 6), (3, 8), (4, 0)])


In [ ]:
# .pop() method removes key:value pairs with key passed inside pop method as argument

In [22]:
a={1:5,2:21,2:6,3:8,4:0}
a.keys()
b=a.items()
print(a.pop(3))
print(a)

8
{1: 5, 2: 6, 4: 0}


# To print random output within a given series and append them in a list

In [23]:
import random

#Returns random value everytime as output between values(1,10) passed & both start & end values are included.

c=[]
for i in range(1,21):
    b=random.randint(1,20)
    c.append(b)
print(c)

[20, 5, 8, 1, 3, 13, 11, 16, 14, 3, 20, 20, 7, 1, 20, 18, 6, 7, 20, 7]


In [19]:
a=[18, 7, 6, 1, 19, 6, 17, 3, 8, 2, 2, 19, 18, 13, 14, 10, 11, 18, 12, 19]
a.sort(reverse=True)
print(a)
a1=[19, 19, 19, 18, 18, 18, 17, 14, 13, 12, 11, 10, 8, 7, 6, 6, 3, 2, 2, 1]
      

[19, 19, 19, 18, 18, 18, 17, 14, 13, 12, 11, 10, 8, 7, 6, 6, 3, 2, 2, 1]


In [55]:
a=['this', 'is', 'a', 'learnbay','class']
b=[]
index=0
for i in a[index]:
    index+=1
print(index)

4


# Pattern printing codes

In [3]:
# pattern printing using nested for loop
#Nested for loop when we want to run inner condition multiple times for single iteration of outer loop
 
for i in range(1,7):
    for j in range(5,0,-1): 
        print('$ '*j)
    if  j == 1:
        break

$ $ $ $ $ 
$ $ $ $ 
$ $ $ 
$ $ 
$ 


In [4]:
# improved version than previous
for i in range(1):
    for j in range(5,0,-1):
        print('*'*j)

*****
****
***
**
*


In [19]:
#Improved version using nested for loop //taking inputs from user and no restrictions on pattern as it Depends on user input
n=int(input("Enter any num:"))
for i in range(1):
    for j in range(n,0,-1):
        print('* '*j)

Enter any num:10
* * * * * * * * * * 
* * * * * * * * * 
* * * * * * * * 
* * * * * * * 
* * * * * * 
* * * * * 
* * * * 
* * * 
* * 
* 


In [8]:
i = 5
while i <= 5:
    if i == 0:
        break
    print("* "*i)
    i-=1
    

* * * * * 
* * * * 
* * * 
* * 
* 


In [7]:
i = 5
while i <= 5:
    print("* "*i)
    i-=1
    if i == 0:
        break

* * * * * 
* * * * 
* * * 
* * 
* 


In [15]:
#Improved version than previous // Taking inputs from user for pattern printing
i = int(input("Enter any num:"))
while i <= 5:
    print("* "*i)
    i-=1
    if i == 0:
        break
else:
    print("Num out of range")

Enter any num:5
* * * * * 
* * * * 
* * * 
* * 
* 


In [20]:
for i in range(1,6):
    print('* '*i)
    

* 
* * 
* * * 
* * * * 
* * * * * 


In [68]:
#White space also needs to be printed alongwith * Note:Whitespaces gets reduced from 4 to 0 & * increases from 1 to 5  from top to bottom
for i in range(1,6):
        print(' '*(5-i),"* "*i) 


     * 
    * * 
   * * * 
  * * * * 
 * * * * * 


# To check if num is positive,negative or zero

In [79]:
a=int(input("Enter a num:"))
for i in range(a,a+1):
    if i>0:
        print(" Num is positive")
    elif i<0:
        print("Num is negative")
    else:
        print("Num is zero")
        

Enter a num:0
Num is zero


# To check Leap Year or not

In [21]:
year = int(input("Enter any year:"))
if year % 4 == 0:
    if year % 100 == 0:
        if year % 400 == 0:
            print ("Leap year")
        else:
            print("Not a Leap Year")
    else:
        print("Leap Year")
else:
    print("It's Not a Leap Year") # Always use different font if same statements needs to be printed twice

Enter any year:2022
It's Not a Leap Year


# Fibonacci Series 

In [8]:
def fib(n):
    a = 0
    b = 1
    if n > 0:
        for i in range(1,n):
            c = a + b    # Carrying out fibonacci ('c' will be carried out fibonacci till the entire 'for' loop iterates)
            a = b        # auto incrementing 'a' by assigning it to 'b'
            b = c        # auto incrementing 'b' by assigning it to 'c'
        return b
    if n <= 0:
        print("wrong input")
    if n == 1:
        return b       
print(fib(1))
print(fib(9)) 

1
34


# Sum of n natural numbers

In [12]:
a=0
b=int(input("Enter a num:"))
for i in range(1,b+1):
    a+=i
#   print(a) This is a continuous print condition given inside for loop and prints o/p at every single condition execution
print(a) #This will generate o/p at the complete execution of for loop
    

Enter a num:5
15


# Sum of n natural numbers

In [11]:
a=0
b=int(input("Enter a num:"))
for i in range(1,b+1):
    a+=i
    print(a) #This is a continuous print condition given inside for loop and prints o/p at every single condition execution

Enter a num:5
1
3
6
10
15


# Use of .split() method for string

In [11]:
a="This is Shashank Sadadekar"
a1=a.split('s') #Lowercase s gets eliminated
a2=a.split()
print(a1)
print(a2)

['Thi', ' i', ' Sha', 'hank Sadadekar']
['This', 'is', 'Shashank', 'Sadadekar']


In [37]:
a="This is Shashank Sadadekar"
b=''
for i in a:
    if i != " ":
        b+=i 
        
else:
    print(b)                              #Output printed with whitespaces removed
    print(type(b))
    c=print(list(b))                      #Output printed with whitespaces removed in list format
    print(type(list(b)))

ThisisShashankSadadekar
<class 'str'>
['T', 'h', 'i', 's', 'i', 's', 'S', 'h', 'a', 's', 'h', 'a', 'n', 'k', 'S', 'a', 'd', 'a', 'd', 'e', 'k', 'a', 'r']
<class 'list'>


# Replace all blank spaces in a str with hyphen

In [21]:
a="This is Shashank Sadadekar"
b=''
for i in a:
    if i == " ":
        b=a.replace(" ",'-')
print(b)


This-is-Shashank-Sadadekar


# Replace all blank spaces in a str with hyphen - Other method

In [24]:
a="This is Shashank Sadadekar"
b=''
for i in range(len(a)):
    if a[i] == " ":
        b=a.replace(" ",'-')
print(b)


This-is-Shashank-Sadadekar


# Str converted into dict key:value pair with count of letters in given str

In [16]:
a="This is Shashank Sadadekar"
b = {}
for i in a:
    if i not in b:
        b[i] = 1
    else:
        b[i] += 1 
print(b)

{'T': 1, 'h': 3, 'i': 2, 's': 3, ' ': 3, 'S': 2, 'a': 5, 'n': 1, 'k': 2, 'd': 2, 'e': 1, 'r': 1}


# BMI calculation using user defined function

In [6]:
Weight = float(input("Enter weight (Kg):"))
Height = float(input("Enter height (m):"))
def BMI():
    BMI = Weight / (Height ** 2)
    '''round() function used to round off the value after decimal to 2 digits'''
    if BMI <= 18.50:
        print("You are underweight")
    elif 18.51 <= BMI <= 24.90:
        print("Congrats!! You are Healthy")
    elif 24.91 <= BMI <= 29.90:
        print("You are overweight")
    else:
        print("Oops!! You are obese")
    return 'Your BMI is:', round(BMI,2)
BMI()

Enter weight (Kg):70
Enter height (m):1.70
Congrats!! You are Healthy


('Your BMI is:', 24.22)

# User defined parameterised func to find max num in given num set

In [7]:
def max_num(a,b,c):
            if (a>b and a>c):
                print('a is max')
            elif (b>c and b>a):
                print('b is max')
            elif (c>a and c>b):
                print('c is max')
            else :
                print('pls provide correct input')
max_num(0,0,0)
max_num(0,-2,-1)
max_num(0,1,2)  

pls provide correct input
a is max
c is max


# Swap first & last element in list using user def func

In [8]:
a=['This', 'is', 'Learnbay']
def swap():
    '''Swapping first & last element'''
    a[0],a[2] = a[2],a[0]
    print(a)
swap()

['Learnbay', 'is', 'This']


# Ascending order bubblesorted list using user def function

In [12]:
#Ascending Sort
def sort_list(a):
    for i in range(len(a)):
        for j in range(i+1,len(a)):
            if a[i] >a[j]:
                a[i],a[j] = a[j],a[i]
    return a
sort_list([1,2,0,-2,4,87,56,65,10])


[-2, 0, 1, 2, 4, 10, 56, 65, 87]

# Descending order sorted list using user def function

In [13]:
#Descending Sort
def sort_list(a):
    for i in range(len(a)):
        for j in range(i+1,len(a)):
            if a[i] <a[j]:
                a[i],a[j] = a[j],a[i]
    return a
sort_list([1,2,0,-2,4,87,56,65,10])

[87, 65, 56, 10, 4, 2, 1, 0, -2]

In [1]:
principal = float(input("Enter principal amt:"))
period = float(input("Enter period in years:"))
int_rate = float(input("Enter int rate:"))
def SI():
    Final_Amt = 0.0
    SI = (principal*period*int_rate)/100
    Final_Amt += SI
    print(Final_Amt)
SI()

Enter principal amt:10000
Enter period in years:10
Enter int rate:10
10000.0


# Calculator Program

In [1]:
n1=float(input("Enter value 1: "))
n2=float(input("Enter value 2: "))
print("Enter desired operation:\n >>> Press 1 for ADD\n >>> Press 2 for SUB\n >>> Press 3 for MUL\n >>> Press 4 for DIV")
a =input()
if a == '1':
    n3 = n1+n2
    print(n3)
elif a =='2':
    n3 = n1-n2
    print(n3)
elif a == '3':
    n3 = n1*n2
    print(n3)
elif a == '4':
    n3 = n1/n2
    print(n3)
else:
    print("Please check your input")

Enter value 1: 5
Enter value 2: 6
Enter desired operation:
 >>> Press 1 for ADD
 >>> Press 2 for SUB
 >>> Press 3 for MUL
 >>> Press 4 for DIV
3
30.0


# Separately print odd string from given input 

In [13]:
a=input("Enter a string:")
b=''
c=''
for i in range(len(a)):
    if i%2 == 0:
        b = b + a[i]      
    else:
        c = c + a[i]
        
print('Even string is:',b)

print('Odd string is:',c)

Enter a string:Shashank123
Even string is: Sahn13
Odd string is: hsak2


# List Intersection

In [9]:
a=['shashank',1,3,'4']
b=['shashank',5,'3','4',1]
c=[]
for i in a:
    for j in b:
        if i != j:
            continue
        else:
            c.append(i)
print('Intersection elements in both lists found:',c)   

Intersection elements in both lists found: ['shashank', 1, '4']


# List Union

In [36]:
a=['shashank',1,3,'4']
b=['shashank',5,'3','4',1]
a.extend(b)    #extend function to make the list union
print(set(a))  #set function to remove duplicates


{1, 3, 5, 'shashank', '4', '3'}


#  To form a new string of first 2 & last 2 characters from a given string

In [10]:
a=input("Enter any string:")
i = 0
j = len(a) -1
b = ''
c = ''
d = ''
while i >= 0:
    b += a[i]
    i += 1
    if i == 2:
        break
while j <= 10:
    c += a[j]
    j -= 1
    if j == 8:
        break
d = d+b+c

print("First & last characters of str:", d)

Enter any string:Shashank123
First & last characters of str: Sh32


In [5]:
a = ['Learnbay', '5', 4, 3, '5', 2]
b =[]
for i in a:
    if a.count('i') == 2:
        a.remove(i)
    else:
        b.append(i)        
print(b)


['Learnbay', '5', 4, 3, '5', 2]


# remove ith occurence of given words where words can repeat

In [27]:
a = ['Learnbay', '5', 4, 3, '5', 2]
for i in a:
    if a.count(i) == 2:
        a.remove(i)
print(a)    

['Learnbay', 4, 3, '5', 2]


In [3]:
# Keyword args

In [2]:
def func(x = 1, y = 2):
    x = x + y
    y += 1
    print(x, y)
func(y = 2, x = 1)

3 3


In [28]:
def f(a=1, b=1, c=1): #All keyword args
    pass
f()

# File Handling

In [6]:
My_File = open("Python.txt",'w+')
print("File name:",My_File.name)
print("File mode:",My_File.mode)
print("File status:",My_File.closed)  # This only checks if file is closed or open & returns bool o/p

File name: Python.txt
File mode: w+
File status: False


In [32]:
My_File.write('Python file handling (a.k.a File I/O) is one of the essential topics for programmers and automation testers. It is required to work with files for either writing to a file or read data from it')

192

In [33]:
My_File.tell()

192

In [35]:
My_File.seek(2)

2

In [38]:
My_File.close()  # Explicitly calling everytime required to close the file once all our file operations are completed

In [39]:
My_File.closed

True

# Recommended

In [ ]:
# For 'with' block, no need to use filename.close() method explicitly as the file gets closed automatically once interpreter comes out of with block of code 

In [ ]:
#Syntax: with open("File_name",'mode') as variable:

In [67]:
with open("Python.txt","w+") as sample_file:
    sample_file.write("Log files are a great tool to debug large programs. It’s always better to think about a scalable design from the beginning, as you won’t regret it later that you didn’t do it.")
    print(sample_file.tell())
    print(sample_file.seek(10))
    print(sample_file.tell())
    print(sample_file.read(5))       # characters upto argument is read. No argument means this method reads till last
    print(sample_file.readline(5))   # Next line from live cursor position is read till the argument given
    print(sample_file.readlines(10)) # No argument is required as it reads all the remaining lines
    print(sample_file.closed)        # Here sample_file is still open so retuned False as with block of code is not completed
print(sample_file.closed)            # Here sample_file is closed so retuned True as 'with' block of code is completed

175
10
10
are a
 grea
['t tool to debug large programs. It’s always better to think about a scalable design from the beginning, as you won’t regret it later that you didn’t do it.']
False
True


In [65]:
sample_file.closed   

True

In [85]:
#If any exception occurs code exits without closing file so use try-finally block to close the file & exit code
try:
    sample_file = open("file1",'w+')
    sample_file.write('''automated software testing.

Let’s take an example,''')
    print(sample_file.read(3))
finally:
    sample_file.close() 

In [86]:
sample_file.closed

True

In [117]:
try:
    sample_file = open("Python.txt","w+")
    sample_file.write("Log files are a great tool to debug large programs.")
    print(sample_file.read())
    print(sample_file.tell())
    sample_file.seek(0)
    print(sample_file.read())
    print(sample_file.tell())
    '''Append & write operation'''
    sample_file = open("Python.txt","a+")
    print(sample_file.write('It’s always better to think about a scalable design from the beginning'))
    print(sample_file.tell())
    print(sample_file.seek(0))
    print(sample_file.readline(0))
    print(sample_file.readlines())
    print(sample_file.closed)
finally:
    sample_file.close()
sample_file.closed


51
Log files are a great tool to debug large programs.
51
70
121
0

['Log files are a great tool to debug large programs.It’s always better to think about a scalable design from the beginning']
False


True

# To read total letters in a file including space

In [2]:
sample_file = open("Python.txt","w+")
sample_file.write("Log files are a great tool to debug large programs.")
count1= 0
sample_file.write("Hello World")
for i in sample_file:
    for j in i:
            count1+=1
else:
    print(i,"\nCount of Letters:",count1,"\nCurrent Cursor at:",sample_file.tell())

Log files are a great tool to debug large programs.Hello World 
Count of Letters: 62 
Current Cursor at: 124


In [7]:
sample_file.close()

In [4]:
sample_file.close()

In [5]:
import os
os.getcwd()

'C:\\Users\\HP\\Python'

# To read number of total lines in a text file created

In [12]:
with open(r"C:\\Users\\HP\\Python\\myfile.txt",'r') as var: # raw string to be declared with r as it contains \(escape seq char)
    a = len(var.readlines())
print(a)

8


In [1]:
import os
print(os.getcwd())

C:\Users\HP\Python


# To copy one file contents into another

In [37]:
var1 = open(r"C:\Users\HP\Python\File1.txt","r") 
a = var1.readlines()
var2 = open(r"C:\Users\HP\Python\File2.txt","w")
var2.writelines(a)
print(var2)
var1.close()
var1.closed
var2.close()
var2.closed

<_io.TextIOWrapper name='C:\\Users\\HP\\Python\\File2.txt' mode='w' encoding='cp1252'>


True

In [38]:
import os
print(os.getcwd())

C:\Users\HP\Python


# To count repetitive words in a text file

In [136]:
var1 = open(r"C:\Users\HP\Python\File1.txt","r+")
a=var1.read()
b=a.count("Python")
print(b)        

2


# To count blank spaces in a text file

In [135]:
var1 = open(r"C:\Users\HP\Python\File1.txt","r+")
a=var1.read()
b=a.count(" ")
print(b)

56


In [26]:
var1 = open(r"C:\Users\HP\Python\File1.txt","r+")
a=var1.read()
b = a.capitalize()
print(b)

FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\HP\\Python\\File1.txt'

In [34]:
var1 = open("Python.txt",'w+')
a = var1.read()
var1.close()

In [35]:
var1.closed

True

In [36]:
import os
os.getcwd()

'C:\\Users\\HP\\Python'

# Reading File content and capitalize first letter of each word

In [18]:
var1 = open(r"C:\\Users\\HP\\Python\\File.txt",'w+')
b= var1.write("Hi shashank")
var1.seek(0)
print(var1.read())
print(var1.tell())

Hi shashank
11


# Python interview questions from python.org site

# To find repeated numbers & print them

In [8]:
a=[1,2,2,3,2,4,5,5,6,7,0,7,0]
b=[]
for i in range(len(a)):
    for j in range(i+1,len(a)):
        if a[i] == a[j]:
            b.append(a[i])
        else:
            continue
print(list(set(b)))

[0, 2, 5, 7]


# If list contains an integer passed

In [31]:
a=[1,2,3,4,5]
def lst_contents(b,c):
    for i in a:
        if i == b:
            return f"List a contains {b} and does not contain {c}"
        elif i == c:
            return f"List a contains {c} and does not contain {b}"
    else:
        return "Pls enter correct values"
print(lst_contents(7,0))
print(lst_contents(7,3))
print(lst_contents(5,-1))

Pls enter correct values
List a contains 3 and does not contain 7
List a contains 5 and does not contain -1


# To find max number

In [4]:
def min_max():
    a= [1,2,3,4,5,5]
    b= [2,6,7,8,4,5]
    if a > b: 
        return f"Max num is {a}"
    elif a < b:
        return f"Min num is {a}"
    elif b > a: 
        return f"Max num is {b}"
    else:
        return f"Min num is {b}"
min_max()

'Max num is [2, 6, 7, 8, 4, 5]'

In [3]:
a=[1,2,3,4,5,'shashank',3+5j]
c=int()
for i in range(len(a)):
    for j in range(i+1,len(a)):
        print(a[i],a[j])

1 2
1 3
1 4
1 5
1 shashank
1 (3+5j)
2 3
2 4
2 5
2 shashank
2 (3+5j)
3 4
3 5
3 shashank
3 (3+5j)
4 5
4 shashank
4 (3+5j)
5 shashank
5 (3+5j)
shashank (3+5j)


# To check anagram or not

In [42]:
def anagram(a,b):
    if sorted(a) == sorted(b):
        return "anagram"
    else:
        return "Not anagram"
anagram("a gentleman", "elegant man")

'anagram'

# Numpy Practice codes

# To know numpy version on your system

In [97]:
import numpy as np
np.__version__

'1.20.3'

In [98]:
import pandas as pd
pd.__version__

'1.3.4'

# To reverse an array

In [116]:
a= np.array([11,12,13,14,15])
a

array([11, 12, 13, 14, 15])

In [123]:
a[15::-1]

array([15, 14, 13, 12, 11])

# To convert list & tuple into arrays

In [29]:
a = [11,12,13,14,15]
b = 11,12,13,14,15
print(type(a),type(b))
c = np.array(a)
d = np.array(b)
print("list to array>>>",type(c), c)
print("tuple to array>>>",type(d),d)

<class 'list'> <class 'tuple'>
list to array>>> <class 'numpy.ndarray'> [11 12 13 14 15]
tuple to array>>> <class 'numpy.ndarray'> [11 12 13 14 15]


# Program to find common values between 2 arrays

In [2]:
import numpy as np
a = [11,12,13,14,15]
b = 1,2,13,4,15
c = np.array(a)
d = np.array(b)

i = 0
while i <= 5:
    if c[i] == d[i]:
        print(f"Element found {c[i]}")
    else:
        print(f"Element not found {c[i]}")
    i += 1
    if i == 5:
        break

Element not found 11
Element not found 12
Element found 13
Element not found 14
Element found 15


# Compare 2 arrays

In [2]:
import numpy as np
a = [11,12,13,14,15]
b = 1,2,13,4,15
c = np.array(a)
d = np.array(b)
print(c == d)
print('\v')
print(np.greater_equal(c,d))
print('\v')
print(np.greater(c,d))
print('\v')
print(np.less_equal(c,d))
print('\v')
print(np.less(c,d))

[False False  True False  True]

[ True  True  True  True  True]

[ True  True False  True False]

[False False  True False  True]

[False False False False False]


# To change dimension of an array

In [22]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
print(a.ndim)
print(a.shape)
print(a.size)

1
(10,)
10


In [29]:
a = np.arange(10).reshape(2,-1,5)
a

array([[[0, 1, 2, 3, 4]],

       [[5, 6, 7, 8, 9]]])

In [30]:
a.ndim

3

# To find sum of 3 & 5 multiples below 100

In [45]:
a = np.arange(1,100)
b = a[(a%3==0) | (a%5==0)]   #In numpy, biwise Or (|)
print(b)

[ 3  5  6  9 10 12 15 18 20 21 24 25 27 30 33 35 36 39 40 42 45 48 50 51
 54 55 57 60 63 65 66 69 70 72 75 78 80 81 84 85 87 90 93 95 96 99]


In [ ]:
# Alternate method

In [4]:
a = np.arange(1,100)
b = a%3 == 0
c = a%5 == 0
d = np.bitwise_or(b,c)      # This will print only True or False
e = a[np.bitwise_or(b,c)]   # Use of bitwise_or method
print(d)
print(e)

[False False  True False  True  True False False  True  True False  True
 False False  True False False  True False  True  True False False  True
  True False  True False False  True False False  True False  True  True
 False False  True  True False  True False False  True False False  True
 False  True  True False False  True  True False  True False False  True
 False False  True False  True  True False False  True  True False  True
 False False  True False False  True False  True  True False False  True
  True False  True False False  True False False  True False  True  True
 False False  True]
[ 3  5  6  9 10 12 15 18 20 21 24 25 27 30 33 35 36 39 40 42 45 48 50 51
 54 55 57 60 63 65 66 69 70 72 75 78 80 81 84 85 87 90 93 95 96 99]


# To convert Numpy array into Python List Structure

In [12]:
a = np.arange(1,10)
a.tolist()

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [17]:
a = np.arange(1,21).reshape(5,4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

# Adding extra columns into an existing numpy array 

In [36]:
a = np.array([[10,20,30],[40,50,60]])
b = np.array([[100],[200]])
print(np.append(a,b,axis = 1))

[[ 10  20  30 100]
 [ 40  50  60 200]]


In [65]:
a = np.array([[0,-1,30],[20,40,60]])
b = np.zeros_like(a)
print(a,'\n','\n',b)   #To create some extra newline space
print()                #To create some extra newline space
print(a==b)

[[ 0 -1 30]
 [20 40 60]] 
 
 [[0 0 0]
 [0 0 0]]

[[ True False False]
 [False False False]]


In [75]:
a=np.random.rand(3,4)
a

array([[0.13705356, 0.33002029, 0.04412727, 0.23058193],
       [0.68886667, 0.36840746, 0.03081362, 0.26392389],
       [0.49389222, 0.94349819, 0.62876351, 0.34367904]])

# To normalise a random 3x3 matrix

In [84]:
import numpy as np
x= np.random.random((3,3))
print("Original Array:")
print(x)
xmax, xmin = x.max(), x.min()
x = (x - xmin)/(xmax - xmin)
print("After normalization:")
print(x)

Original Array:
[[0.69191825 0.78006665 0.45135654]
 [0.08857257 0.98466714 0.95561816]
 [0.76882503 0.42335796 0.69735461]]
After normalization:
[[0.67330582 0.77167534 0.4048501 ]
 [0.         1.         0.96758269]
 [0.75913021 0.37360497 0.67937254]]


# To find transpose from row to column

In [2]:
import numpy as np
np_arr1 = np.array([1,2,3,4])
np_arr2 = np.array([5,6,7,8])
print(np.column_stack((np_arr1, np_arr2)))

[[1 5]
 [2 6]
 [3 7]
 [4 8]]


# to swap 2 rows of an array

In [130]:
a = np.array([[10,20,30],[40,50,60]])
a[[0,1]] = a[[1,0]] 
a

array([[40, 50, 60],
       [10, 20, 30]])

# To sort a random array 

In [151]:
a=np.random.rand(2,5)
print(a)
np.sort(a)

[[0.91217041 0.26008145 0.77868081 0.35120391 0.01064189]
 [0.75137762 0.44054627 0.44415677 0.52621359 0.24314255]]


array([[0.01064189, 0.26008145, 0.35120391, 0.77868081, 0.91217041],
       [0.24314255, 0.44054627, 0.44415677, 0.52621359, 0.75137762]])

In [183]:
a=np.random.rand(1,3)
b = np.random.rand(3,1)
print(a)
print()
print(b)
print()
print(np.equal(a,b))       # 1st Option
print()
print(a == b)              # 2nd Option
print()
print(np.allclose(a,b))    # 3rd Option

[[0.95425917 0.95397354 0.80586178]]

[[0.16160506]
 [0.12685187]
 [0.90741502]]

[[False False False]
 [False False False]
 [False False False]]

[[False False False]
 [False False False]
 [False False False]]

False


# To perform arithmatic operations element wise

In [203]:
a = np.array([[10,20,30],[40,50,60]])
b = np.arange(6).reshape(2,-1)
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(b,a))

[[10 21 32]
 [43 54 65]]
[[10 19 28]
 [37 46 55]]
[[  0  20  60]
 [120 200 300]]
[[0.         0.05       0.06666667]
 [0.075      0.08       0.08333333]]


# To get yesterday, today, tomm years

In [224]:
import numpy as np
Yesterday = np.datetime64('Today','Y') - np.timedelta64(1,"Y")
Today = np.datetime64('Today','Y') 
Tomm = np.datetime64('Today','Y') + np.timedelta64(1,"Y")
print(Yesterday)
print(Today)
print(Tomm)

2021
2022
2023


 # To get yesterday, today, tomm months

In [227]:
import numpy as np
Yesterday = np.datetime64('Today','M') - np.timedelta64(1,"M")
Today = np.datetime64('Today','M') 
Tomm = np.datetime64('Today','M') + np.timedelta64(1,"M")
print(Yesterday)
print(Today)
print(Tomm)

2022-02
2022-03
2022-04


 # To get yesterday, today, tomm dates

In [229]:
import numpy as np
Yesterday = np.datetime64('Today','D') - np.timedelta64(1,"D")
Today = np.datetime64('Today','D') 
Tomm = np.datetime64('Today','D') + np.timedelta64(1,"D")
print(Yesterday)
print(Today)
print(Tomm)

2022-03-12
2022-03-13
2022-03-14


# Pandas Codes

# To create 1D array using Pandas Module

In [234]:
import pandas as pd
Data = np.arange(15,10,-1)
var = pd.Series(Data)
var

0    15
1    14
2    13
3    12
4    11
dtype: int32

# To convert Pandas Series to list

In [242]:
var1 = pd.Series.tolist(var)
var1

[15, 14, 13, 12, 11]

# To perform Arithmatic Operations on 2 Pandas series

In [249]:
var

0    15
1    14
2    13
3    12
4    11
dtype: int32

In [245]:
var2 = pd.Series([10,11,12,13,14])
var2

0    10
1    11
2    12
3    13
4    14
dtype: int64

In [248]:
print(var+var2)
print(var-var2)
print(var*var2)
print(var/var2)

0    25
1    25
2    25
3    25
4    25
dtype: int64
0    5
1    3
2    1
3   -1
4   -3
dtype: int64
0    150
1    154
2    156
3    156
4    154
dtype: int64
0    1.500000
1    1.272727
2    1.083333
3    0.923077
4    0.785714
dtype: float64


# To compare elements of 2 pandas Series

In [261]:
print(var > var2,'\n')
print(var < var2,'\n')
print(var >= var2,'\n')
print(var <= var2,'\n')
print(var == var2)

0     True
1     True
2     True
3    False
4    False
dtype: bool 

0    False
1    False
2    False
3     True
4     True
dtype: bool 

0     True
1     True
2     True
3    False
4    False
dtype: bool 

0    False
1    False
2    False
3     True
4     True
dtype: bool 

0    False
1    False
2    False
3    False
4    False
dtype: bool


In [265]:
import pandas as pd
Data = np.arange(16,10,-1).reshape(2,3)
var = pd.DataFrame(Data,index = ['i','ii'])
var

0   1   2
i   16  15  14
ii  13  12  11

In [271]:
import pandas as pd
Data = np.arange(16,10,-1).reshape(2,3)
var = pd.DataFrame({'Nos':[Data]})
var

Nos
0  [[16, 15, 14], [13, 12, 11]]

In [324]:
import pandas as pd
# Data = np.arange(16,10,-1).reshape(2,3)
var = pd.DataFrame({'Nos':[11,12,13], "Emp Id":[6952, 678, 1234], "Name":['Shashank','Uday','Sadadekar']},index = ['s','U','S'])
var

Nos  Emp Id       Name
s   11    6952   Shashank
U   12     678       Uday
S   13    1234  Sadadekar

# Selecting specific rows & col from given DF using .loc or .iloc methods

In [329]:
var.loc['U':'S','Emp Id':'Name']   #For explicit indexing, we use loc

Emp Id       Name
U     678       Uday
S    1234  Sadadekar

In [333]:
var.iloc[1:,1:]      #implicit index if used for slicing rows & columns we use iloc

Emp Id       Name
U     678       Uday
S    1234  Sadadekar

In [335]:
dict = {'Year':['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec']}
months = pd.DataFrame(dict,index = ['J','F','M','A','Ma','J','Ju','Au','S','O','N','D'])
months

Year
J   Jan
F   Feb
M   Mar
A   Apr
Ma  May
J   Jun
Ju  Jul
Au  Aug
S   Sep
O   Oct
N   Nov
D   Dec

In [344]:
months.loc['Ma':'O'] # .loc() includes both start & stop index

Year
Ma  May
J   Jun
Ju  Jul
Au  Aug
S   Sep
O   Oct

In [342]:
months.iloc[5:10] #.iloc() excludes start index

Year
J   Jun
Ju  Jul
Au  Aug
S   Sep
O   Oct

In [1]:
import pandas as pd
dict = {'State Name':['GJ',"MH","DL","KA","TN"],'Capital Name':['Ahm','Bom','Agr',"Bng","Chn"]}
df = pd.DataFrame(dict)
df

State Name Capital Name
0         GJ          Ahm
1         MH          Bom
2         DL          Agr
3         KA          Bng
4         TN          Chn

# Adding new rows to existing DF

In [27]:
df.loc[5] = ["KL",'Koc']
df

State Name Capital Name
0         GJ          Ahm
1         MH          Bom
2         DL          Agr
3         KA          Bng
4         TN          Chn
6         KL          Koc
5         KL          Koc

In [46]:
df = df.sort_index(ascending = False)     # Reverse sorting
df

State Name Capital Name
4         TN          Chn
3         KA          Bng
2         DL          Agr
1         MH          Bom

# To add columns to existing DF

In [48]:
df["City Names"] = ["Chennai",'Bengaluru','Agra','Bombay']
df

State Name Capital Name City Names
4         TN          Chn    Chennai
3         KA          Bng  Bengaluru
2         DL          Agr       Agra
1         MH          Bom     Bombay

In [55]:
df.rename(columns = {'Capital Name':'City Code'})

State Name City Code City Names
4         TN       Chn    Chennai
3         KA       Bng  Bengaluru
2         DL       Agr       Agra
1         MH       Bom     Bombay

# To delete rows from existing DF

In [57]:
df = df.drop([1])
df

State Name Capital Name City Names
4         TN          Chn    Chennai
3         KA          Bng  Bengaluru
2         DL          Agr       Agra

# Change Name of Bengaluru to Bangalore in City Names

In [61]:
df['City Names'][3] = 'Bangalore'
df

State Name Capital Name City Names
4         TN          Chn    Chennai
3         KA          Bng  Bangalore
2         DL          Agr       Agra

# To find common letters in 2 input strings

In [51]:
a = 'Hello World'
b = 'This is Python Class'
c = set(a) & set(b)
print(c)

{'o', 'l', ' '}


# To display letters in first Str but not in second

In [90]:
a = 'Hello World'
b = 'This is Python Class'
for i in a:
    if i not in b:
        print(i)  

H
e
W
r
d


#Alternate Solution for above program

In [60]:
a = 'Hello World'
b = 'This is Python Class'
c = set(a) - set(b)
print(c)

{'H', 'd', 'W', 'e', 'r'}


# Which letters are present in both Str

In [88]:
a = 'Hello World'
b = 'This is Python Class' 
c = (set(a) | set(b))
c

{' ',
 'C',
 'H',
 'P',
 'T',
 'W',
 'a',
 'd',
 'e',
 'h',
 'i',
 'l',
 'n',
 'o',
 'r',
 's',
 't',
 'y'}

# Letters are in 2 strings but not in both

In [87]:
a = 'Hello World'
b = 'This is Python Class'
c = set(a) ^ set(b)
print(c)

{'h', 's', 'H', 'i', 'n', 'W', 'a', 'C', 'T', 'y', 'd', 't', 'e', 'r', 'P'}


In [30]:
var1 = open(r"C:\\Users\\HP\\Python\\File.txt",'w+')
b= var1.write("Hi shashank")
var1.seek(0)
print(var1.read())
print(var1.tell())
var1 = open(r"C:\\Users\\HP\\Python\\File.txt",'a+')
var1.write("How r u doing this evening?")
var1.seek(0)
var1.read()
var1.close()

Hi shashank
11


In [60]:
var1 = open(r"C:\\Users\\HP\\Python\\File.txt",'w+')
b= var1.write("Hi shashank")
var1.seek(0)
print(var1.read())
print(var1.tell())
var1 = open(r"C:\\Users\\HP\\Python\\File.txt",'a+')
var1.write("\nHow r u doing this evening?")
var1.seek(0)
var1.read()
File1.close()
File.close()

Hi shashank
11


NameError: name 'File1' is not defined

# Decorators (Decorate or modify the value of any func i.e p(m) here)

In [6]:
def f(x):
    def f1(*args, **kwargs):
        print("*"* 5)
        x(*args, **kwargs)
        print("*"* 5)
    return f1
def a(x):
    def f1(*args, **kwargs):
        print("%"* 5)
        x(*args, **kwargs)
        print("%"* 5)
    return f1
@f 
@a
def p(m):
    print(m)
p("hello")

*****
%%%%%
hello
%%%%%
*****
